<html>
<head>
    <meta charset="utf-8">
    <title>Report Generation</title>
    <style>
        
        body {
            text-align: center;
        }
    </style>

    <!-- DataTables CSS from a CDN -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css">
</head>
<body>
    <form action="raport_czaspracy.php" method="post">
        <label for="stockdate">Wybierz date:</label>
        <input type="date" name="stockdate" value="<?php echo date('Y-m-d'); ?>" required>
        <input type="submit" name="tabela" value="TABELA" />
        <input type="submit" name="wyszukaj" value="EXCEL" />
    </form>

    <?php
    require 'vendor/autoload.php';

    use PhpOffice\PhpSpreadsheet\IOFactory;

    if (isset($_POST['tabela'])) {
        $param1 = $_POST['stockdate'];
        $output = exec("python raport_czaspracy.py '$param1'");

        // Load the Excel file generated by Python using PhpSpreadsheet
        $spreadsheet = IOFactory::load($output);

        //  data from the Excel file
        $worksheet = $spreadsheet->getActiveSheet();
        $rows = $worksheet->toArray();

        // Display the data as an HTML table with DataTables
        echo '<table id="excel-table" class="display" style="width:100%">';
        echo '<thead><tr>';
        foreach ($worksheet->getRowIterator() as $row) {
            foreach ($row->getCellIterator() as $cell) {
                echo '<th>' . htmlspecialchars($cell->getValue()) . '</th>';
            }
            break; // Only get headers from the first row
        }
        echo '</tr></thead>';
        echo '<tbody>';

		$isFirstRow = true; // Flag to identify the first row

        foreach ($rows as $row) {
			if ($isFirstRow) {
				$isFirstRow = false;
				continue; // Skip the first row
			}
		
			echo '<tr>';
			foreach ($row as $cell) {
				echo '<td>' . htmlspecialchars($cell) . '</td>';
			}
			echo '</tr>';
        }
        echo '</tbody></table>';
    }

    if (isset($_POST['wyszukaj'])) {
        $param1 = $_POST['stockdate'];
        $output = exec("python raport_czaspracy.py '$param1'");

		echo $output;

        // Download the generated Excel file
        header('Content-Description: File Transfer');
        header('Content-Type: application/octet-stream');
        header('Content-Disposition: attachment; filename=czas_pracy.xlsx'); 
        header('Content-Transfer-Encoding: binary');
        header('Expires: 0');
        header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
        header('Pragma: public');
        header('Content-Length: ' . filesize($output));
        ob_clean();
        flush();
        readfile($output);
        unlink($output);
        exit();
    }
    ?>

    <!--  jQuery (required for DataTables) from a CDN -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <!--  DataTables JavaScript from a CDN -->
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script>
        $(document).ready(function() {
            var table = $('#excel-table').DataTable();

            // Enable column filtering
            table.columns().every(function() {
                var column = this;
                var select = $('<select><option value=""></option></select>')
                    .appendTo($(column.header()))
                    .on('change', function() {
                        var val = $.fn.dataTable.util.escapeRegex($(this).val());
                        column.search(val ? '^' + val + '$' : '', true, false).draw();
                    });

                column.data().unique().sort().each(function(d, j) {
                    select.append('<option value="' + d + '">' + d + '</option>');
                });
            });
        });
    </script>
</body>
</html>
